# Generated by Django 3.0.10 on 2020-10-28 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201028_1243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created', 'user')},
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
    ]
